---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ghost
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
    nginx.ingress.kubernetes.io/ssl-passthrough: "true"
    nginx.ingress.kubernetes.io/backend-protocol: "HTTPS"
spec:
  ingressClassName: nginx
  tls:
    - hosts: 
      - wallpaper.local
      secretName: tlsenabled
  rules:
  - host: wallpaper.local
    http:
      paths:
      - path: / 
        pathType: Prefix
        backend:
          service:
            name: ghost
            port:
              number: 80
