apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pvc
  labels:
    app: mysql
spec:
  storageClassName: mysql-local
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  selector:
    matchLabels:
      name: mysql-pv
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-pvc
  labels:
    app: ghost
spec:
  storageClassName: ghost-local
  resources:
    requests:
      storage: 2Gi
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  selector:
    matchLabels:
      name: ghost-pv